### ISSUE TITLE
[Bug] Wi-fi icon in Gnome

### ISSUE THREAD

**Issue by btd1337** [zayronxio/Mkos-Big-Sur#15]
In Gnome 3.38, just low signal icon is showing to wi-fi

![Captura de tela de 2020-12-22 15-22-46](https://user-images.githubusercontent.com/11943860/102920557-b393e100-4469-11eb-9dea-9012c6eafb7f.png)

**Comment by zayronxio** [comment]
corrected, please confirm if it has also been fixed for you

**Comment by btd1337** [comment]
@zayronxio Now it looks like this:

![Captura de tela de 2021-01-02 18-33-46](https://user-images.githubusercontent.com/11943860/103467016-56314700-4d29-11eb-9bf7-d527b54ecf31.png)

The battery icon don't looks with mac OS. Are you did any change in it?

Below is a screenshot of the [Whitesur Icon Theme](https://github.com/vinceliuice/WhiteSur-icon-theme):

![Captura de tela de 2021-01-02 18-34-17](https://user-images.githubusercontent.com/11943860/103467049-b922de00-4d29-11eb-80f4-369258dae3f6.png)

**Comment by zayronxio** [comment]
I have not made any changes to the battery icon, I must check the error

**Comment by zayronxio** [comment]
last commit add more battery icons, please try

**Comment by btd1337** [comment]
Although It icon don't be so clear in `1366x768`, at least now been setting for correct icon.

![Captura de tela de 2021-01-03 19-04-08](https://user-images.githubusercontent.com/11943860/103489934-10db4b00-4df7-11eb-868b-a0a74582d5ed.png)

As the initial request was fulfilled, I want to thank you for your good work and I will close the issue.

If you want to make improvements to any icons, it can be done separately.

---

### Mkos Big Sur

![Captura de tela de 2021-01-03 19-09-04](https://user-images.githubusercontent.com/11943860/103490084-24d37c80-4df8-11eb-9065-853b138969c5.png)

### White Sur

![Captura de tela de 2021-01-03 19-09-29](https://user-images.githubusercontent.com/11943860/103490087-3026a800-4df8-11eb-88f4-3cdfd2d8a5db.png)
