### ISSUE TITLE
Can you please make 16x16 as filled icons as in macOS

### ISSUE THREAD

**Issue by pavangayakwad** [zayronxio/Mkos-Big-Sur#21]
Currently the folders look like this when we reduced view to 50%
![image](https://user-images.githubusercontent.com/1834890/125647265-11dca52f-4a95-4ed6-8595-df80e013743d.png)

It would be great if the folder icons looks like in actual macOS
![image](https://user-images.githubusercontent.com/1834890/125647765-7172fb72-769b-41ef-9519-8078ef62bd48.png)

**Comment by zayronxio** [comment]
unfortunately doing what you request implies losing compatibility with xfce4
