### ISSUE TITLE
Icon theme don't show en Settings - Debian 11 Xfce4

### ISSUE THREAD

**Issue by iRo0t** [zayronxio/Mkos-Big-Sur#23]
Hi, I have copied the theme to home/.local/share/icons. and it does not show up in Settings/Appearance/Icons.
Then I copied to /usr/share/icons, and it doesn't show up to select it either.

I am using Debian 11 Stable with Xfce4.

**Comment by zayronxio** [comment]
you need to make sure you are copying the proper folder, inside the folder it should contain the index.theme file and subdirectories
