### ISSUE TITLE
Corrupt XZ and icon mismatch?

### ISSUE THREAD

**Issue by jcfrosty** [zayronxio/Mkos-Big-Sur#4]
There are only a couple things I've noticed that were "off" that cause me to reduce the rating. 

1. unxz and KDE both tell me that this XZ file is corrupt which requires one to manually download from the KDE store and forcefully extract the contents and move them to the /usr/share/icons folder. I'm using app-arch/xz-utils-5.2.5 . 

2. The wireshark icon doesn't appear to match up or fit with the rest and the quassel IRC client icon seems to use the "konversation" icon with is very confusing and also doesn't match or fit the rest of the icon theme. 

Thank you for your time and effort. This is a fantastic Icon theme!

**Comment by zayronxio** [comment]
wireshark icon has been added and xz file on pling.com has been fixed
