### ISSUE TITLE
Audio Icon Is Bluerry Under GNOME 3.36

### ISSUE THREAD

**Issue by qingxiang-jia** [zayronxio/Mkos-Big-Sur#5]
The audio icon is blurry with GNOME 3.36. Other icon themes seem to handle this properly. Can we fix this?
Thanks!
![sample](https://user-images.githubusercontent.com/5571586/87898877-484e6a80-ca04-11ea-8263-018326937bbd.png)

**Comment by zayronxio** [comment]
the problem may be related to the index, I have changed it, please try

**Comment by qingxiang-jia** [comment]
Will do, thank you!

**Comment by zayronxio** [comment]
if the problem can warn me or close the issues

**Comment by zayronxio** [comment]
if the problem has been fixed, you can report or close the issues

**Comment by qingxiang-jia** [comment]
hello~ i just pulled from the master and unfortunately the problem still persists. i recorded a gif in case it helps.
![Peek 2020-07-20 19-24](https://user-images.githubusercontent.com/5571586/88005820-0df5d380-cabf-11ea-8217-8ff232863e6c.gif)

**Comment by zayronxio** [comment]
You just made a modification, can you try again?

**Comment by totalfreak** [comment]
I tried the modification, it fixes the normal audio icon, but the over amplified icon is still like before (blurry)

**Comment by qingxiang-jia** [comment]
Hi @zayronxio , thanks for fixing it. I will update.
@totalfreak thanks for trying!

**Comment by qingxiang-jia** [comment]
Hi @zayronxio , I just confirmed what @totalfreak said.

**Comment by zayronxio** [comment]
bug resolved
