### ISSUE TITLE
Too many icons are in non-square shape. Please transform them.

### ISSUE THREAD

**Issue by thrdroom** [zayronxio/Mkos-Big-Sur#8]
Hi @zayronxio 
Thank you so much for your great work on the macos icon packs ❤

There are still way too many icons that are in circle or non-square shape.
The original big sur icons are **all in square shape**. Please take a look at the attached screenshot.

Also there are some icons which look really bad/ugly imho, like the "Signal-Messenger" icon, or the KeepassXC icon. Can we please fix those icons? I have attached a zip file with svg icons i created for some missing applications and some that fit the design scheme of big sur better. Some of them have 2 different versions to choose from.
@zayronxio Please replace existing icons with the better ones from my zip file.

Thank you :)

**New Icons**
[Missing-Broken-Icons-And-Better-Icons-Mkos-Big-Sur.zip](https://github.com/zayronxio/Mkos-Big-Sur/files/5135838/Missing-Broken-Icons-And-Better-Icons-Mkos-Big-Sur.zip)

**Screenshot**
![dock-ugly-round-icons](https://user-images.githubusercontent.com/5912061/91432500-15e52800-e862-11ea-8e22-53a8377cad70.png)

**Comment by zayronxio** [comment]
Thanks for your contribution before, I will add these icons, thank you very much for your contribution, and change these icons as much as possible. sometimes free time is not enough.

**Comment by zayronxio** [comment]
add some icons that you have asked me, add more as soon as possible

**Comment by thrdroom** [comment]
If you want i can contribute/transform more icons in my freetime. What would be the correct way to submit new icons to you, and what is the right way to contact you? Have a nice day.

**Comment by zayronxio** [comment]
Thanks for your interest, you can make an extraction request right here on github, or if you prefer to send me mail. Telegram is also an option, look for zayronxio

**Comment by zayronxio** [comment]
Could you tell me which icons on your desktop are not square yet?

**Comment by zayronxio** [comment]
Today, the set does not cover all apps but it will soon
